management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info   # or "*" to expose all (quote the *)
      base-path: /public/actuator

info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'