
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect4-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect4-java
  template:
    metadata:
      labels:
        app: connect4-java
    spec:
      containers:
        - name: connect4-java
          image: biplopdey/connect4-java:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /public/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /public/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
