name: 'Smoke Test (Lite)'
inputs:
  url:
    description: 'Base URL to test'
    required: true
  version:
    description: 'Optional: version to expect in /public/actuator/info'
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        set -e
        URL="${{ inputs.url }}"
        VERSION="${{ inputs.version }}"
        for i in {1..30}; do
          if curl -fs "$URL/public/actuator/health" | grep -q '"status":"UP"'; then
            if [ -z "$VERSION" ]; then
              echo "✓ Health OK (no version check)"
              exit 0
            else
              if curl -fs "$URL/public/actuator/info" | grep -q "$VERSION"; then
                echo "✓ Actuator health and version OK"
                exit 0
              fi
            fi
          fi
          echo "Waiting the service to start… ($i/30)"
          sleep 1
        done
        echo "The service did not respond"
        exit 1

