name: Pmd,Test,Sonar, build and push jar to artifactory
run-name: running spring boot version
on: [ push ]
jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Run PMD
        run: mvn --batch-mode -DskipTests pmd:pmd pmd:check
      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: target/pmd.xml
          retention-days: 1

  test:
    needs: pmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Run test
        run: mvn --batch-mode test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Package the app
        run: mvn --batch-mode -DskipTests verify
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload artifactory with it's corresponding tag version
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1
        
