name: eks-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        uses: aws-actions/eks-update-kubeconfig@v2
        with:
          cluster-name: ${{ vars.EKS_CLUSTER }}
          region: ${{ vars.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/connect4-java connect4-java=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
