name: eks-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.version }}
      CLUSTER_NAME: ${{ vars.EKS_CLUSTER }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster if needed
        run: |
          eksctl get cluster --name "$CLUSTER_NAME" --region ${{ vars.AWS_REGION }} || \
          eksctl create cluster --name "$CLUSTER_NAME" --region ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name "$CLUSTER_NAME" \
            --region ${{ vars.AWS_REGION }}

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/connect4-java connect4-java=docker.io/biplopdey/connect4-java:${{ env.IMAGE_TAG }}

      - name: Wait for service URL
        id: service
        run: |
          set -e
          for i in {1..60}; do
            HOST=$(kubectl get svc connect4-java -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$HOST" ]; then
              echo "url=http://$HOST" >> "$GITHUB_OUTPUT"
              exit 0
            fi
            echo "Waiting for service. ($i/60)"
            sleep 5
          done
          echo "Service load balancer hostname not available" >&2
          exit 1

      - name: Test actuator endpoints
        uses: ./.github/actions/smoke-test
        with:
          url: ${{ steps.service.outputs.url }}
          version: ${{ env.IMAGE_TAG }}
