name: app-runner-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: app-runner-image-deploy-service # will be created or updated
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          access-role-arn: ${{ secrets.ROLE_ARN }}  # IAM role that lets App Runner pull from your (private) ECR repo
          region: ${{ vars.AWS_REGION }}
          cpu: 1
          memory: 2
          port: 8080
          wait-for-service-stability-seconds: 600

      - name: App Runner output
        run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}"

      - name: Test actuator endpoints
        uses: ./.github/actions/smoke-test
        with:
          url: https://${{ steps.deploy-apprunner.outputs.service-url }}
          version: ${{ env.IMAGE_TAG }}
