name: docker-publish

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Package the app
        run: mvn --batch-mode verify
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload artifactory
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1

  docker:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep -oP '(?<=<version>)[^<]+' pom.xml | sed -n 2p)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/connect4-java:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/connect4-java:latest

      - name: Verify tags are available
        run: |
          set -e
          docker pull ${{ env.REGISTRY }}/connect4-java:${{ steps.version.outputs.version }}
          docker pull ${{ env.REGISTRY }}/connect4-java:latest
      - name: Test actuator endpoints
        run: |
          set -e
          IMAGE=${{ env.REGISTRY }}/connect4-java:${{ steps.version.outputs.version }}

          echo "Running container…"
          CID=$(docker run -d -p 8080:8080 "$IMAGE")

          for i in {1..30}; do
            if curl -fs http://localhost:8080/public/actuator/health | grep -q '"status":"UP"'; then
              if curl -fs http://localhost:8080/public/actuator/info | grep -q "${{ steps.version.outputs.version }}"; then
                echo "✅ Actuator endpoints OK"
                docker stop "$CID"
                exit 0
              fi
            fi
            echo "Waiting the app to start… ($i/30)"
            sleep 1
          done

          echo "The app did not respond"
          docker logs "$CID"
          docker stop "$CID"
          exit 1