name: Pmd,Test,Sonar, build and push jar to artifactory
run-name: running spring boot version
on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'
jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Run PMD
        run: mvn --batch-mode -DskipTests pmd:check
      - name: Upload PMD report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report-${{ github.run_number }}
          path: target/pmd.xml
          retention-days: 1

  test:
    needs: pmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
      - name: Run test
        run: mvn --batch-mode test